### ISSUE TITLE
Unchecked canvas items turn on when swiping

### ISSUE THREAD

**Issue by jctull** [lmotta/mapswipetool_plugin#10]
This seems to be a bug to me, but if a layer in a folder is turned off, the swipe tool turns that layer on when swiping. I may have a folder with 5 items, but only want 4 of them drawing. The swipe tool draws all of them.

**Comment by lmotta** [comment]
It was fixed for next version (release for QGIS 3.4).
If the layer is turned off  inside Group, it will invisible when its group will be choice
