### ISSUE TITLE
MapSwipe Tool does not properly align both images 

### ISSUE THREAD

**Issue by ShannonRice** [lmotta/mapswipetool_plugin#11]
Running Mac 10.13.6  - QGIS 3.4 (although I've experienced issue in QGIS 3.6.1 as well.)   When i have perfectly aligned images set to visible, and attempt to use the Mapswipe tool, it displays one of the images offset signficantly from correct location.  (so basically, it doesn't work for me).    Attached is a screenshot. Please let me know if you have suggestions.  I've tried uninstalling, and reinstalling, and nothing allow me to use this, what would be a very useful tool.) 

Best, 
Shannon

![Screen Shot 2019-04-09 at 3 42 43 PM](https://user-images.githubusercontent.com/2422354/55830502-0d5e4700-5adf-11e9-97ba-fd741ea66de9.png)

**Comment by Clarmy** [comment]
I encountered the same problem.

**Comment by Nie7yang** [comment]
Sorry, I rediscovered the same problem on the M1 Mac using macOS13.2.1 today, the current QGIS version is 3.30, and the MapSwipe Tool is 1.2.
Best,
Nie

**Comment by osgav** [comment]
I had this problem as well, but I've figured out a fix. 

After the following lines in `swipemap.py` in the `setMap` function…

```
settings = QgsMapSettings( self.canvas.mapSettings() )
settings.setLayers( self.layers )
settings.setBackgroundColor( QColor( Qt.transparent ) )
```

…add this line:

```
settings.setDevicePixelRatio( 1 )
```

For reference I'm on Fedora Linux 35 (GNOME 41.6, Wayland), QGIS 3.22.8 and MapSwipe Tool 1.2.

https://osgav.run/blog/qgis-plugin-mapswipe-tool.html

**Comment by felupion** [comment]
> I had this problem as well, but I've figured out a fix.
> 
> After the following lines in `swipemap.py` in the `setMap` function…
> 
> ```
> settings = QgsMapSettings( self.canvas.mapSettings() )
> settings.setLayers( self.layers )
> settings.setBackgroundColor( QColor( Qt.transparent ) )
> ```
> 
> …add this line:
> 
> ```
> settings.setDevicePixelRatio( 1 )
> ```
> 
> For reference I'm on Fedora Linux 35 (GNOME 41.6, Wayland), QGIS 3.22.8 and MapSwipe Tool 1.2.
> 
> https://osgav.run/blog/qgis-plugin-mapswipe-tool.html

@osgav Tks a lot! it worked on my MAC

**Comment by ccl-private** [comment]
MapSwipe Tool 1.3 still have this problem. my qgis is 3.42.0.

**Comment by ccl-private** [comment]
why this issues closed.@lmotta

**Comment by christro** [comment]
I have still the same problem with Mac OS and also with Windows
QGIS 3.42.4
Map Swipe Tool 1.3
