### ISSUE TITLE
Mapswipe crashes Qgis 3.2 for mac

### ISSUE THREAD

**Issue by mr-foxycat** [lmotta/mapswipetool_plugin#13]
I'm unable to use your plugin. 
Qgis 3.20 for macOS 11.5.2 > instant crash when clicking icon for mapswipe. Have installed latest version of python3 -did not help.. 
(i did not make python3 the system default -im not a complete geek so it puzzles me how to do so.. but both version 2.7 and 3.9 of python is installed on the system)

Should your plugin work with python 2.7 or does it require python3+ ?
Can anyone hint at me what is broken?

Crash report: 
[mapswipe-qgis320-crashreport.txt](https://github.com/lmotta/mapswipetool_plugin/files/7128355/mapswipe-qgis320-crashreport.txt)

**Comment by lmotta** [comment]
Hi,

In QGIS 3.x migrated of Python 2.7 to 3.x, so, all plugins  migrated too.

Did you use the plugin in LTR version(3.16.x)?

I update my plugin when new LTR version is launched.

**Comment by mr-foxycat** [comment]
Thank you very much for a quick reply 
- running 3.16 LTR does the trick
