### ISSUE TITLE
white background

### ISSUE THREAD

**Issue by gioman** [lmotta/mapswipetool_plugin#3]
If the swiping layer is a vector, then were there are no features the background is white. See attached image

![swipe1](https://cloud.githubusercontent.com/assets/1951107/10515738/b925b0ec-734c-11e5-81b0-e53e05904c7d.png)

**Comment by lmotta** [comment]
Create a group with 2 layers, landuse and Ortofotomapas, active this group.
The active layer/group ever will be added above the others layers, and, all yours layers will be visible( independent of legend)

**Comment by gioman** [comment]
I see your point. Anyway if you think is worth (and feasible) I think it is more straightforward to have a transparent background for the swiping layer. If not possible then close the ticket, but I would suggest to add a note on the plugin readme otherwise users will not likely understand how to get the desired affect. Cheers!

**Comment by lmotta** [comment]
The swipe layer is  a curtain, where opens or closes the view of the layers as they are defined in the legend.
The curtain is formed by a layer or group of layers.
Technically, we put a QgsMapCanvasMap above the existing.
At the moment, we will put the note in the readme.
Thanks

**Comment by lmotta** [comment]
It was fixed  for next version (release for QGIS 3.4).
The user can use the vector layer with transparent background
