### ISSUE TITLE
cannot switch swiping layer/group

### ISSUE THREAD

**Issue by gioman** [lmotta/mapswipetool_plugin#5]
After having activated for the first time the swiping layer/group then is not possible to change it. Clicking the plugin button has no effect. Starting a new project too. The only solution is to close and reopen qgis.

**Comment by lmotta** [comment]
Has a bug in some OS, i use the Kubuntu 14.04, for change the active layer, change the map tool(ex. Pan) and back to Swipe tool.
Sorry for this inconvenient.
